### ISSUE TITLE
Not compatible with VS 2022 17.9.x

### ISSUE THREAD

**Issue by pommetjehorlepiep** [WayneKoorts/Scratchy#2]
Microsoft Visual Studio Professional 2022 (64-bit) - Current
Version 17.9.1

[dd_VSIXInstaller_20240226143101_55ac.log](https://github.com/WayneKoorts/Scratchy/files/14399686/dd_VSIXInstaller_20240226143101_55ac.log)

**Comment by WayneKoorts** [comment]
I'll fix this within the next day or two, sorry for the inconvenience.

**Comment by pommetjehorlepiep** [comment]
> I'll fix this within the next day or two, sorry for the inconvenience.

Excellent. Thx for the very quick response. 

Love Scratchy! Something I've wanted for VS for ages.

**Comment by WayneKoorts** [comment]
> > I'll fix this within the next day or two, sorry for the inconvenience.
> 
> Excellent. Thx for the very quick response.
> 
> Love Scratchy! Something I've wanted for VS for ages.

That makes me happy to hear, thank you so much!

**Comment by pommetjehorlepiep** [comment]
Sorry @WayneKoorts, but it seems the 1.4.0 version still needs some additional work...

![image](https://github.com/WayneKoorts/Scratchy/assets/8982487/41751b63-be3e-4159-9d31-bf771872417b)
[dd_VSIXInstaller_20240228065907_2bac.log](https://github.com/WayneKoorts/Scratchy/files/14425631/dd_VSIXInstaller_20240228065907_2bac.log)

**Comment by WayneKoorts** [comment]
Damn, sorry about that, I'll have a look soon.

**Comment by WayneKoorts** [comment]
@pommetjehorlepiep I think I found the issue, could you please try v1.4.1 and see if it works now?

**Comment by pommetjehorlepiep** [comment]
> @pommetjehorlepiep I think I found the issue, could you please try v1.4.1 and see if it works now?

Just installed version 1.4.1 successfully and it's working as expected!

Thx @WayneKoorts for the quick resolution!
